name: 💡请求帮助
description: 请求帮助
labels: ['help wanted']
body:
  - type: checkboxes
    attributes:
      label: 是否有已经存在的问题
      description: 请使用搜索功能查阅是否存在和您一致或相似的问题
      options:
        - label: 我已经查阅了 https://github.com/phantom-sea-limited/Crawler/issues
          required: true
        - label: 我已经查阅了互联网，但并没有得到解决方案
          required: true
  - type: textarea
    id: message
    attributes:
      label: 描述问题
      description: 任何需要的东西请在此添加
      placeholder: |-
        请尽可能详细描述问题
    validations:
      required: false
    attributes:
      value: |-
        ## Thanks 🙏
